function wnode = gen_whitening_nodes(patchDim)

rawImages = load_images;

% whitening nodes are generated by sampling image patches
fprintf('Generating whitening nodes...\n')
imgNo4wnodes=100000;
x = sample_images(rawImages, imgNo4wnodes, patchDim);
x = log(x+2);
x = x - repmat(mean(x,1),imgNo4wnodes,1);

x = reshape(x, size(x,1), size(x,2)*size(x,3));

% calculate the sample mean and covariance matrix for the data
% x_bar = mean(x);
sigma = cov(x);
% Get the eigenvectors and corresponding eigenvalues for this data.
[U, lambda] = eig(sigma);
% Whiten the data by applying the following linear transform. and plot the
% result.

wnode = U*lambda^(-.5)*U';
% wnode = lambda^(-.5)*U;

save(sprintf('wnodes_%d.mat',patchDim^2),'wnode');
