function samplePatches


% %%
% clear all
% 
% patchDim = 8;
% 
% %%% Reset random seeds 
% rand('state',sum(100*clock)); 
% randn('state',sum(100*clock)); 
% 
% rawImages = load_images;
% 
% % whitening nodes are generated by sampling image patches
% fprintf('Generating whitening nodes...\n')
% imgNo4wnodes=100000;
% x = sample_images(rawImages, imgNo4wnodes, patchDim);
% x = log(x+2);
% x = x - repmat(mean(x,1),imgNo4wnodes,1);
% wnode = gen_whitening_nodes(x);
% clear x imgNo4wnodes
% fprintf('Done.');
% fprintf('\n');
% 
% %%
% % making batches of image patches for training
% 
% trainingLength = 800*80;
% % trainingLength = 150000;
% batchLength = 800;
% 
% fprintf('Generating batches of data...\n')
% 
% numBatches = trainingLength/batchLength;
% numDims = patchDim^2;
% batchData = zeros(numDims, batchLength, numBatches);
% for i=1:numBatches
%     fprintf('\b\b\b\b%4d',i);
%     x = sample_images(rawImages, batchLength, patchDim);
%     x = log(x+2);
%     x = x - repmat(mean(x,1),batchLength,1);
%     x = reshape(x,batchLength,patchDim^2);
%     xw = do_whitening(x,wnode);
%     batchData(:,:,i) = xw';
% end
% clear rawImages x xw
% fprintf('\nDone.');
% fprintf('\n');